export interface NseStockMaster {
  symbol: string;         // e.g. 'RELIANCE.NS'
  cleanSymbol: string;    // e.g. 'RELIANCE'
  name: string;           // e.g. 'Reliance Industries Limited'
  sector: string;         // e.g. 'Energy'
  capTier: 'LARGE_CAP' | 'MID_CAP' | 'SMALL_CAP' | 'MICRO_CAP';
  isFno: boolean;
  series: string;         // e.g. 'EQ', 'BE', 'SM'
  isin?: string;
}

export const ALL_NSE_STOCKS: NseStockMaster[] = [
  // --- NIFTY 50 & MEGA/LARGE CAPS ---
  { symbol: 'RELIANCE.NS', cleanSymbol: 'RELIANCE', name: 'Reliance Industries Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TCS.NS', cleanSymbol: 'TCS', name: 'Tata Consultancy Services Ltd.', sector: 'IT', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HDFCBANK.NS', cleanSymbol: 'HDFCBANK', name: 'HDFC Bank Ltd.', sector: 'Nifty Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ICICIBANK.NS', cleanSymbol: 'ICICIBANK', name: 'ICICI Bank Ltd.', sector: 'Nifty Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BHARTIARTL.NS', cleanSymbol: 'BHARTIARTL', name: 'Bharti Airtel Ltd.', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'INFY.NS', cleanSymbol: 'INFY', name: 'Infosys Ltd.', sector: 'IT', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ITC.NS', cleanSymbol: 'ITC', name: 'ITC Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SBIN.NS', cleanSymbol: 'SBIN', name: 'State Bank of India', sector: 'PSU Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'LICI.NS', cleanSymbol: 'LICI', name: 'Life Insurance Corporation of India', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HINDUNILVR.NS', cleanSymbol: 'HINDUNILVR', name: 'Hindustan Unilever Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'LT.NS', cleanSymbol: 'LT', name: 'Larsen & Toubro Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BAJFINANCE.NS', cleanSymbol: 'BAJFINANCE', name: 'Bajaj Finance Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HCLTECH.NS', cleanSymbol: 'HCLTECH', name: 'HCL Technologies Ltd.', sector: 'IT', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MARUTI.NS', cleanSymbol: 'MARUTI', name: 'Maruti Suzuki India Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SUNPHARMA.NS', cleanSymbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd.', sector: 'Nifty Pharma', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'M&M.NS', cleanSymbol: 'M&M', name: 'Mahindra & Mahindra Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'KOTAKBANK.NS', cleanSymbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd.', sector: 'Nifty Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'AXISBANK.NS', cleanSymbol: 'AXISBANK', name: 'Axis Bank Ltd.', sector: 'Nifty Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TITAN.NS', cleanSymbol: 'TITAN', name: 'Titan Company Ltd.', sector: 'Consumer Durables', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TMPV.NS', cleanSymbol: 'TMPV', name: 'Tata Motors Passenger Vehicles Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TATAMOTORS.NS', cleanSymbol: 'TATAMOTORS', name: 'Tata Motors Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'NTPC.NS', cleanSymbol: 'NTPC', name: 'NTPC Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ONGC.NS', cleanSymbol: 'ONGC', name: 'Oil & Natural Gas Corporation Ltd.', sector: 'Oil & Gas', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'POWERGRID.NS', cleanSymbol: 'POWERGRID', name: 'Power Grid Corporation of India Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ADANIENT.NS', cleanSymbol: 'ADANIENT', name: 'Adani Enterprises Ltd.', sector: 'Commodities', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ADANIPORTS.NS', cleanSymbol: 'ADANIPORTS', name: 'Adani Ports and SEZ Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ADANIGREEN.NS', cleanSymbol: 'ADANIGREEN', name: 'Adani Green Energy Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ADANIENSOL.NS', cleanSymbol: 'ADANIENSOL', name: 'Adani Energy Solutions Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ATGL.NS', cleanSymbol: 'ATGL', name: 'Adani Total Gas Ltd.', sector: 'Oil & Gas', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ADANIPOWER.NS', cleanSymbol: 'ADANIPOWER', name: 'Adani Power Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'COALINDIA.NS', cleanSymbol: 'COALINDIA', name: 'Coal India Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BAJAJFINSV.NS', cleanSymbol: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BAJAJ-AUTO.NS', cleanSymbol: 'BAJAJ-AUTO', name: 'Bajaj Auto Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ASIANPAINT.NS', cleanSymbol: 'ASIANPAINT', name: 'Asian Paints Ltd.', sector: 'Consumption', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TATASTEEL.NS', cleanSymbol: 'TATASTEEL', name: 'Tata Steel Ltd.', sector: 'Metal', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'JSWSTEEL.NS', cleanSymbol: 'JSWSTEEL', name: 'JSW Steel Ltd.', sector: 'Metal', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HINDALCO.NS', cleanSymbol: 'HINDALCO', name: 'Hindalco Industries Ltd.', sector: 'Metal', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'VEDL.NS', cleanSymbol: 'VEDL', name: 'Vedanta Ltd.', sector: 'Metal', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SIEMENS.NS', cleanSymbol: 'SIEMENS', name: 'Siemens Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ABB.NS', cleanSymbol: 'ABB', name: 'ABB India Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HAL.NS', cleanSymbol: 'HAL', name: 'Hindustan Aeronautics Ltd.', sector: 'Defence', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BEL.NS', cleanSymbol: 'BEL', name: 'Bharat Electronics Ltd.', sector: 'Defence', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TRENT.NS', cleanSymbol: 'TRENT', name: 'Trent Ltd.', sector: 'Consumption', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'VBL.NS', cleanSymbol: 'VBL', name: 'Varun Beverages Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ZOMATO.NS', cleanSymbol: 'ZOMATO', name: 'Zomato Ltd. (Eternal)', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ETERNAL.NS', cleanSymbol: 'ETERNAL', name: 'Eternal Ltd. (Zomato)', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'JIOFIN.NS', cleanSymbol: 'JIOFIN', name: 'Jio Financial Services Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'DMART.NS', cleanSymbol: 'DMART', name: 'Avenue Supermarts Ltd. (DMart)', sector: 'Consumption', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'NESTLEIND.NS', cleanSymbol: 'NESTLEIND', name: 'Nestle India Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'GRASIM.NS', cleanSymbol: 'GRASIM', name: 'Grasim Industries Ltd.', sector: 'Commodities', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ULTRACEMCO.NS', cleanSymbol: 'ULTRACEMCO', name: 'UltraTech Cement Ltd.', sector: 'Nifty Cement', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'AMBUJACEM.NS', cleanSymbol: 'AMBUJACEM', name: 'Ambuja Cements Ltd.', sector: 'Nifty Cement', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ACC.NS', cleanSymbol: 'ACC', name: 'ACC Ltd.', sector: 'Nifty Cement', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SHREECEM.NS', cleanSymbol: 'SHREECEM', name: 'Shree Cement Ltd.', sector: 'Nifty Cement', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'DALBHARAT.NS', cleanSymbol: 'DALBHARAT', name: 'Dalmia Bharat Ltd.', sector: 'Nifty Cement', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TECHM.NS', cleanSymbol: 'TECHM', name: 'Tech Mahindra Ltd.', sector: 'IT', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'WIPRO.NS', cleanSymbol: 'WIPRO', name: 'Wipro Ltd.', sector: 'IT', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'LTIM.NS', cleanSymbol: 'LTIM', name: 'LTIMindtree Ltd.', sector: 'IT', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PERSISTENT.NS', cleanSymbol: 'PERSISTENT', name: 'Persistent Systems Ltd.', sector: 'IT', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'COFORGE.NS', cleanSymbol: 'COFORGE', name: 'Coforge Ltd.', sector: 'IT', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MPHASIS.NS', cleanSymbol: 'MPHASIS', name: 'Mphasis Ltd.', sector: 'IT', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'LTTS.NS', cleanSymbol: 'LTTS', name: 'L&T Technology Services Ltd.', sector: 'IT', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'OFSS.NS', cleanSymbol: 'OFSS', name: 'Oracle Financial Services Software', sector: 'IT', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TATAELXSI.NS', cleanSymbol: 'TATAELXSI', name: 'Tata Elxsi Ltd.', sector: 'IT', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'KPITTECH.NS', cleanSymbol: 'KPITTECH', name: 'KPIT Technologies Ltd.', sector: 'IT', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BSOFT.NS', cleanSymbol: 'BSOFT', name: 'Birlasoft Ltd.', sector: 'IT', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CYIENT.NS', cleanSymbol: 'CYIENT', name: 'Cyient Ltd.', sector: 'IT', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TATATECH.NS', cleanSymbol: 'TATATECH', name: 'Tata Technologies Ltd.', sector: 'IT', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HDFCLIFE.NS', cleanSymbol: 'HDFCLIFE', name: 'HDFC Life Insurance Co. Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SBILIFE.NS', cleanSymbol: 'SBILIFE', name: 'SBI Life Insurance Co. Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ICICIPRULI.NS', cleanSymbol: 'ICICIPRULI', name: 'ICICI Prudential Life Insurance', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ICICIGI.NS', cleanSymbol: 'ICICIGI', name: 'ICICI Lombard General Insurance', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CHOLAFIN.NS', cleanSymbol: 'CHOLAFIN', name: 'Cholamandalam Investment & Finance', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SHRIRAMFIN.NS', cleanSymbol: 'SHRIRAMFIN', name: 'Shriram Finance Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PFC.NS', cleanSymbol: 'PFC', name: 'Power Finance Corporation Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'RECLTD.NS', cleanSymbol: 'RECLTD', name: 'REC Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MUTHOOTFIN.NS', cleanSymbol: 'MUTHOOTFIN', name: 'Muthoot Finance Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HDFCAMC.NS', cleanSymbol: 'HDFCAMC', name: 'HDFC Asset Management Co. Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BSE.NS', cleanSymbol: 'BSE', name: 'BSE Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MCX.NS', cleanSymbol: 'MCX', name: 'Multi Commodity Exchange of India', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CDSL.NS', cleanSymbol: 'CDSL', name: 'Central Depository Services (India)', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CAMS.NS', cleanSymbol: 'CAMS', name: 'Computer Age Management Services', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ANGELONE.NS', cleanSymbol: 'ANGELONE', name: 'Angel One Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: '360ONE.NS', cleanSymbol: '360ONE', name: '360 ONE WAM Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'NUVAMA.NS', cleanSymbol: 'NUVAMA', name: 'Nuvama Wealth Management Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'KFINTECH.NS', cleanSymbol: 'KFINTECH', name: 'KFin Technologies Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },

  // --- BANKS ---
  { symbol: 'BANKBARODA.NS', cleanSymbol: 'BANKBARODA', name: 'Bank of Baroda', sector: 'PSU Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PNB.NS', cleanSymbol: 'PNB', name: 'Punjab National Bank', sector: 'PSU Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CANBK.NS', cleanSymbol: 'CANBK', name: 'Canara Bank', sector: 'PSU Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'UNIONBANK.NS', cleanSymbol: 'UNIONBANK', name: 'Union Bank of India', sector: 'PSU Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'INDIANB.NS', cleanSymbol: 'INDIANB', name: 'Indian Bank', sector: 'PSU Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BANKINDIA.NS', cleanSymbol: 'BANKINDIA', name: 'Bank of India', sector: 'PSU Bank', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CENTRALBK.NS', cleanSymbol: 'CENTRALBK', name: 'Central Bank of India', sector: 'PSU Bank', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'IOB.NS', cleanSymbol: 'IOB', name: 'Indian Overseas Bank', sector: 'PSU Bank', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'UCOBANK.NS', cleanSymbol: 'UCOBANK', name: 'UCO Bank', sector: 'PSU Bank', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'MAHABANK.NS', cleanSymbol: 'MAHABANK', name: 'Bank of Maharashtra', sector: 'PSU Bank', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'PSB.NS', cleanSymbol: 'PSB', name: 'Punjab & Sind Bank', sector: 'PSU Bank', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },

  { symbol: 'INDUSINDBK.NS', cleanSymbol: 'INDUSINDBK', name: 'IndusInd Bank Ltd.', sector: 'Nifty Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'FEDERALBNK.NS', cleanSymbol: 'FEDERALBNK', name: 'The Federal Bank Ltd.', sector: 'Nifty Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'IDFCFIRSTB.NS', cleanSymbol: 'IDFCFIRSTB', name: 'IDFC First Bank Ltd.', sector: 'Nifty Bank', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'AUBANK.NS', cleanSymbol: 'AUBANK', name: 'AU Small Finance Bank Ltd.', sector: 'Nifty Bank', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BANDHANBNK.NS', cleanSymbol: 'BANDHANBNK', name: 'Bandhan Bank Ltd.', sector: 'Nifty Bank', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'RBLBANK.NS', cleanSymbol: 'RBLBANK', name: 'RBL Bank Ltd.', sector: 'Nifty Bank', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'YESBANK.NS', cleanSymbol: 'YESBANK', name: 'Yes Bank Ltd.', sector: 'Nifty Bank', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'KARURVYSYA.NS', cleanSymbol: 'KARURVYSYA', name: 'Karur Vysya Bank Ltd.', sector: 'Private Bank', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CUB.NS', cleanSymbol: 'CUB', name: 'City Union Bank Ltd.', sector: 'Private Bank', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SOUTHBANK.NS', cleanSymbol: 'SOUTHBANK', name: 'The South Indian Bank Ltd.', sector: 'Private Bank', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'KTKBANK.NS', cleanSymbol: 'KTKBANK', name: 'Karnataka Bank Ltd.', sector: 'Private Bank', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'J&KBANK.NS', cleanSymbol: 'J&KBANK', name: 'The Jammu & Kashmir Bank Ltd.', sector: 'Private Bank', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'EQUITASBNK.NS', cleanSymbol: 'EQUITASBNK', name: 'Equitas Small Finance Bank Ltd.', sector: 'Private Bank', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'UJJIVANSFB.NS', cleanSymbol: 'UJJIVANSFB', name: 'Ujjivan Small Finance Bank Ltd.', sector: 'Private Bank', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },

  // --- AUTO & AUTO ANCILLARIES ---
  { symbol: 'EICHERMOT.NS', cleanSymbol: 'EICHERMOT', name: 'Eicher Motors Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TVSMOTOR.NS', cleanSymbol: 'TVSMOTOR', name: 'TVS Motor Company Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HEROMOTOCO.NS', cleanSymbol: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BHARATFORG.NS', cleanSymbol: 'BHARATFORG', name: 'Bharat Forge Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ASHOKLEY.NS', cleanSymbol: 'ASHOKLEY', name: 'Ashok Leyland Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BOSCHLTD.NS', cleanSymbol: 'BOSCHLTD', name: 'Bosch Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MOTHERSON.NS', cleanSymbol: 'MOTHERSON', name: 'Samvardhana Motherson International', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'UNOMINDA.NS', cleanSymbol: 'UNOMINDA', name: 'Uno Minda Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SONACOMS.NS', cleanSymbol: 'SONACOMS', name: 'Sona BLW Precision Forgings', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TIINDIA.NS', cleanSymbol: 'TIINDIA', name: 'Tube Investments of India Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BALKRISIND.NS', cleanSymbol: 'BALKRISIND', name: 'Balkrishna Industries Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MRF.NS', cleanSymbol: 'MRF', name: 'MRF Ltd.', sector: 'Nifty Auto', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'APOLLOTYRE.NS', cleanSymbol: 'APOLLOTYRE', name: 'Apollo Tyres Ltd.', sector: 'Nifty Auto', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CEATLTD.NS', cleanSymbol: 'CEATLTD', name: 'CEAT Ltd.', sector: 'Nifty Auto', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'JKTYRE.NS', cleanSymbol: 'JKTYRE', name: 'JK Tyre & Industries Ltd.', sector: 'Nifty Auto', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'EXIDEIND.NS', cleanSymbol: 'EXIDEIND', name: 'Exide Industries Ltd.', sector: 'Nifty Auto', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'AMARAJABAT.NS', cleanSymbol: 'AMARAJABAT', name: 'Amara Raja Energy & Mobility Ltd.', sector: 'Nifty Auto', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ESCORTS.NS', cleanSymbol: 'ESCORTS', name: 'Escorts Kubota Ltd.', sector: 'Nifty Auto', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ENDURANCE.NS', cleanSymbol: 'ENDURANCE', name: 'Endurance Technologies Ltd.', sector: 'Nifty Auto', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CRAFTSMAN.NS', cleanSymbol: 'CRAFTSMAN', name: 'Craftsman Automation Ltd.', sector: 'Nifty Auto', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },

  // --- PHARMA & HEALTHCARE ---
  { symbol: 'CIPLA.NS', cleanSymbol: 'CIPLA', name: 'Cipla Ltd.', sector: 'Nifty Pharma', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'DRREDDY.NS', cleanSymbol: 'DRREDDY', name: "Dr. Reddy's Laboratories Ltd.", sector: 'Nifty Pharma', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'DIVISLAB.NS', cleanSymbol: 'DIVISLAB', name: "Divi's Laboratories Ltd.", sector: 'Nifty Pharma', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TORNTPHARM.NS', cleanSymbol: 'TORNTPHARM', name: 'Torrent Pharmaceuticals Ltd.', sector: 'Nifty Pharma', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ZYDUSLIFE.NS', cleanSymbol: 'ZYDUSLIFE', name: 'Zydus Lifesciences Ltd.', sector: 'Nifty Pharma', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MANKIND.NS', cleanSymbol: 'MANKIND', name: 'Mankind Pharma Ltd.', sector: 'Nifty Pharma', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'LUPIN.NS', cleanSymbol: 'LUPIN', name: 'Lupin Ltd.', sector: 'Nifty Pharma', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'AUROPHARMA.NS', cleanSymbol: 'AUROPHARMA', name: 'Aurobindo Pharma Ltd.', sector: 'Nifty Pharma', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ALKEM.NS', cleanSymbol: 'ALKEM', name: 'Alkem Laboratories Ltd.', sector: 'Nifty Pharma', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BIOCON.NS', cleanSymbol: 'BIOCON', name: 'Biocon Ltd.', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'GLENMARK.NS', cleanSymbol: 'GLENMARK', name: 'Glenmark Pharmaceuticals Ltd.', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'IPCALAB.NS', cleanSymbol: 'IPCALAB', name: 'IPCA Laboratories Ltd.', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'LAURUSLABS.NS', cleanSymbol: 'LAURUSLABS', name: 'Laurus Labs Ltd.', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'GRANULES.NS', cleanSymbol: 'GRANULES', name: 'Granules India Ltd.', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PPLPHARMA.NS', cleanSymbol: 'PPLPHARMA', name: 'Piramal Pharma Ltd.', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ABBOTINDIA.NS', cleanSymbol: 'ABBOTINDIA', name: 'Abbott India Ltd.', sector: 'Nifty Pharma', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SANOFI.NS', cleanSymbol: 'SANOFI', name: 'Sanofi India Ltd.', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'JBCHEPHARM.NS', cleanSymbol: 'JBCHEPHARM', name: 'J.B. Chemicals & Pharmaceuticals', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'NATCOPHARM.NS', cleanSymbol: 'NATCOPHARM', name: 'Natco Pharma Ltd.', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'AJANTPHARM.NS', cleanSymbol: 'AJANTPHARM', name: 'Ajanta Pharma Ltd.', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ERIS.NS', cleanSymbol: 'ERIS', name: 'Eris Lifesciences Ltd.', sector: 'Nifty Pharma', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'GLAXO.NS', cleanSymbol: 'GLAXO', name: 'GlaxoSmithKline Pharmaceuticals', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'PFIZER.NS', cleanSymbol: 'PFIZER', name: 'Pfizer Ltd.', sector: 'Nifty Pharma', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'NEULANDLAB.NS', cleanSymbol: 'NEULANDLAB', name: 'Neuland Laboratories Ltd.', sector: 'Nifty Pharma', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },

  { symbol: 'APOLLOHOSP.NS', cleanSymbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise Ltd.', sector: 'Healthcare', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MAXHEALTH.NS', cleanSymbol: 'MAXHEALTH', name: 'Max Healthcare Institute Ltd.', sector: 'Healthcare', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'FORTIS.NS', cleanSymbol: 'FORTIS', name: 'Fortis Healthcare Ltd.', sector: 'Healthcare', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MEDANTA.NS', cleanSymbol: 'MEDANTA', name: 'Global Health Ltd. (Medanta)', sector: 'Healthcare', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'KIMS.NS', cleanSymbol: 'KIMS', name: 'Krishna Institute of Medical Sciences', sector: 'Healthcare', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ASTERDM.NS', cleanSymbol: 'ASTERDM', name: 'Aster DM Healthcare Ltd.', sector: 'Healthcare', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'RAINBOW.NS', cleanSymbol: 'RAINBOW', name: "Rainbow Children's Medicare Ltd.", sector: 'Healthcare', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'NH.NS', cleanSymbol: 'NH', name: 'Narayana Hrudayalaya Ltd.', sector: 'Healthcare', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'LALPATHLAB.NS', cleanSymbol: 'LALPATHLAB', name: 'Dr. Lal PathLabs Ltd.', sector: 'Healthcare', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'METROPOLIS.NS', cleanSymbol: 'METROPOLIS', name: 'Metropolis Healthcare Ltd.', sector: 'Healthcare', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SYNGENE.NS', cleanSymbol: 'SYNGENE', name: 'Syngene International Ltd.', sector: 'Healthcare', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'THYROCARE.NS', cleanSymbol: 'THYROCARE', name: 'Thyrocare Technologies Ltd.', sector: 'Healthcare', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },

  // --- ENERGY, POWER & PSU ---
  { symbol: 'TATAPOWER.NS', cleanSymbol: 'TATAPOWER', name: 'Tata Power Company Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'JSWENERGY.NS', cleanSymbol: 'JSWENERGY', name: 'JSW Energy Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'NHPC.NS', cleanSymbol: 'NHPC', name: 'NHPC Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SJVN.NS', cleanSymbol: 'SJVN', name: 'SJVN Ltd.', sector: 'Energy', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SUZLON.NS', cleanSymbol: 'SUZLON', name: 'Suzlon Energy Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'IREDA.NS', cleanSymbol: 'IREDA', name: 'Indian Renewable Energy Dev Agency', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'IRFC.NS', cleanSymbol: 'IRFC', name: 'Indian Railway Finance Corporation', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'RVNL.NS', cleanSymbol: 'RVNL', name: 'Rail Vikas Nigam Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'IRCON.NS', cleanSymbol: 'IRCON', name: 'Ircon International Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'RITES.NS', cleanSymbol: 'RITES', name: 'RITES Ltd.', sector: 'Infra', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'RAILTEL.NS', cleanSymbol: 'RAILTEL', name: 'RailTel Corporation of India Ltd.', sector: 'IT', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'IRCTC.NS', cleanSymbol: 'IRCTC', name: 'Indian Railway Catering & Tourism', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BHEL.NS', cleanSymbol: 'BHEL', name: 'Bharat Heavy Electricals Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TORNTPOWER.NS', cleanSymbol: 'TORNTPOWER', name: 'Torrent Power Ltd.', sector: 'Energy', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'POWERINDIA.NS', cleanSymbol: 'POWERINDIA', name: 'Hitachi Energy India Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CGPOWER.NS', cleanSymbol: 'CGPOWER', name: 'CG Power and Industrial Solutions', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'INOXWIND.NS', cleanSymbol: 'INOXWIND', name: 'Inox Wind Ltd.', sector: 'Energy', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CESC.NS', cleanSymbol: 'CESC', name: 'CESC Ltd.', sector: 'Energy', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'NLCINDIA.NS', cleanSymbol: 'NLCINDIA', name: 'NLC India Ltd.', sector: 'Energy', capTier: 'MID_CAP', isFno: false, series: 'EQ' },

  // --- OIL, GAS & REFINERIES ---
  { symbol: 'BPCL.NS', cleanSymbol: 'BPCL', name: 'Bharat Petroleum Corporation Ltd.', sector: 'Oil & Gas', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'IOC.NS', cleanSymbol: 'IOC', name: 'Indian Oil Corporation Ltd.', sector: 'Oil & Gas', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HINDPETRO.NS', cleanSymbol: 'HINDPETRO', name: 'Hindustan Petroleum Corporation Ltd.', sector: 'Oil & Gas', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'GAIL.NS', cleanSymbol: 'GAIL', name: 'GAIL (India) Ltd.', sector: 'Oil & Gas', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'OIL.NS', cleanSymbol: 'OIL', name: 'Oil India Ltd.', sector: 'Oil & Gas', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PETRONET.NS', cleanSymbol: 'PETRONET', name: 'Petronet LNG Ltd.', sector: 'Oil & Gas', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'IGL.NS', cleanSymbol: 'IGL', name: 'Indraprastha Gas Ltd.', sector: 'Oil & Gas', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MGL.NS', cleanSymbol: 'MGL', name: 'Mahanagar Gas Ltd.', sector: 'Oil & Gas', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'GUJGASLTD.NS', cleanSymbol: 'GUJGASLTD', name: 'Gujarat Gas Ltd.', sector: 'Oil & Gas', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MRPL.NS', cleanSymbol: 'MRPL', name: 'Mangalore Refinery and Petrochemicals', sector: 'Oil & Gas', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CHENNPETRO.NS', cleanSymbol: 'CHENNPETRO', name: 'Chennai Petroleum Corporation Ltd.', sector: 'Oil & Gas', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'AEGISLOG.NS', cleanSymbol: 'AEGISLOG', name: 'Aegis Logistics Ltd.', sector: 'Oil & Gas', capTier: 'MID_CAP', isFno: false, series: 'EQ' },

  // --- METALS & MINING ---
  { symbol: 'JINDALSTEL.NS', cleanSymbol: 'JINDALSTEL', name: 'Jindal Steel & Power Ltd.', sector: 'Metal', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SAIL.NS', cleanSymbol: 'SAIL', name: 'Steel Authority of India Ltd.', sector: 'Metal', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'NMDC.NS', cleanSymbol: 'NMDC', name: 'NMDC Ltd.', sector: 'Metal', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'NATIONALUM.NS', cleanSymbol: 'NATIONALUM', name: 'National Aluminium Co. Ltd.', sector: 'Metal', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HINDZINC.NS', cleanSymbol: 'HINDZINC', name: 'Hindustan Zinc Ltd.', sector: 'Metal', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'APLAPOLLO.NS', cleanSymbol: 'APLAPOLLO', name: 'APL Apollo Tubes Ltd.', sector: 'Metal', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'JSL.NS', cleanSymbol: 'JSL', name: 'Jindal Stainless Ltd.', sector: 'Metal', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'RATNAMANI.NS', cleanSymbol: 'RATNAMANI', name: 'Ratnamani Metals & Tubes Ltd.', sector: 'Metal', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'WELCORP.NS', cleanSymbol: 'WELCORP', name: 'Welspun Corp Ltd.', sector: 'Metal', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'KIRLOSENG.NS', cleanSymbol: 'KIRLOSENG', name: 'Kirloskar Oil Engines Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'MOIL.NS', cleanSymbol: 'MOIL', name: 'MOIL Ltd.', sector: 'Metal', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'KIOCL.NS', cleanSymbol: 'KIOCL', name: 'KIOCL Ltd.', sector: 'Metal', capTier: 'MID_CAP', isFno: false, series: 'EQ' },

  // --- DEFENCE & AEROSPACE ---
  { symbol: 'BDL.NS', cleanSymbol: 'BDL', name: 'Bharat Dynamics Ltd.', sector: 'Defence', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MAZDOCK.NS', cleanSymbol: 'MAZDOCK', name: 'Mazagon Dock Shipbuilders Ltd.', sector: 'Defence', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'COCHINSHIP.NS', cleanSymbol: 'COCHINSHIP', name: 'Cochin Shipyard Ltd.', sector: 'Defence', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'GRSE.NS', cleanSymbol: 'GRSE', name: 'Garden Reach Shipbuilders & Engineers', sector: 'Defence', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SOLARINDS.NS', cleanSymbol: 'SOLARINDS', name: 'Solar Industries India Ltd.', sector: 'Defence', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'DATAPATTNS.NS', cleanSymbol: 'DATAPATTNS', name: 'Data Patterns (India) Ltd.', sector: 'Defence', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'PARAS.NS', cleanSymbol: 'PARAS', name: 'Paras Defence and Space Technologies', sector: 'Defence', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ASTRAMICRO.NS', cleanSymbol: 'ASTRAMICRO', name: 'Astra Microwave Products Ltd.', sector: 'Defence', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ZENITHEXPO.NS', cleanSymbol: 'ZENITHEXPO', name: 'Zen Technologies Ltd.', sector: 'Defence', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ZENTEC.NS', cleanSymbol: 'ZENTEC', name: 'Zen Technologies Ltd.', sector: 'Defence', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'MTARTECH.NS', cleanSymbol: 'MTARTECH', name: 'MTAR Technologies Ltd.', sector: 'Defence', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },

  // --- INFRASTRUCTURE, CAPITAL GOODS & REALTY ---
  { symbol: 'DLF.NS', cleanSymbol: 'DLF', name: 'DLF Ltd.', sector: 'Realty', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'GODREJPROP.NS', cleanSymbol: 'GODREJPROP', name: 'Godrej Properties Ltd.', sector: 'Realty', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'OBEROIRLTY.NS', cleanSymbol: 'OBEROIRLTY', name: 'Oberoi Realty Ltd.', sector: 'Realty', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'LODHA.NS', cleanSymbol: 'LODHA', name: 'Macrotech Developers Ltd. (Lodha)', sector: 'Realty', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PRESTIGE.NS', cleanSymbol: 'PRESTIGE', name: 'Prestige Estates Projects Ltd.', sector: 'Realty', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PHOENIXLTD.NS', cleanSymbol: 'PHOENIXLTD', name: 'The Phoenix Mills Ltd.', sector: 'Realty', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BRIGADE.NS', cleanSymbol: 'BRIGADE', name: 'Brigade Enterprises Ltd.', sector: 'Realty', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SOBHA.NS', cleanSymbol: 'SOBHA', name: 'Sobha Ltd.', sector: 'Realty', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SUNTECK.NS', cleanSymbol: 'SUNTECK', name: 'Sunteck Realty Ltd.', sector: 'Realty', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'MAHLIFE.NS', cleanSymbol: 'MAHLIFE', name: 'Mahindra Lifespace Developers Ltd.', sector: 'Realty', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'IBREALEST.NS', cleanSymbol: 'IBREALEST', name: 'Indiabulls Real Estate Ltd.', sector: 'Realty', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'NBCC.NS', cleanSymbol: 'NBCC', name: 'NBCC (India) Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'NCC.NS', cleanSymbol: 'NCC', name: 'NCC Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CUMMINSIND.NS', cleanSymbol: 'CUMMINSIND', name: 'Cummins India Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'POLYCAB.NS', cleanSymbol: 'POLYCAB', name: 'Polycab India Ltd.', sector: 'Consumer Durables', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'KEI.NS', cleanSymbol: 'KEI', name: 'KEI Industries Ltd.', sector: 'Consumer Durables', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HAVELLS.NS', cleanSymbol: 'HAVELLS', name: 'Havells India Ltd.', sector: 'Consumer Durables', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'DIXON.NS', cleanSymbol: 'DIXON', name: 'Dixon Technologies (India) Ltd.', sector: 'Consumer Durables', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'VOLTAS.NS', cleanSymbol: 'VOLTAS', name: 'Voltas Ltd.', sector: 'Consumer Durables', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BLUESTARCO.NS', cleanSymbol: 'BLUESTARCO', name: 'Blue Star Ltd.', sector: 'Consumer Durables', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CROMPTON.NS', cleanSymbol: 'CROMPTON', name: 'Crompton Greaves Consumer Electricals', sector: 'Consumer Durables', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'AMBER.NS', cleanSymbol: 'AMBER', name: 'Amber Enterprises India Ltd.', sector: 'Consumer Durables', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'KAYNES.NS', cleanSymbol: 'KAYNES', name: 'Kaynes Technology India Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PGEL.NS', cleanSymbol: 'PGEL', name: 'PG Electroplast Ltd.', sector: 'Consumer Durables', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CONCOR.NS', cleanSymbol: 'CONCOR', name: 'Container Corporation of India Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'GMRAIRPORT.NS', cleanSymbol: 'GMRAIRPORT', name: 'GMR Airports Infrastructure Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'IRB.NS', cleanSymbol: 'IRB', name: 'IRB Infrastructure Developers Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'KEC.NS', cleanSymbol: 'KEC', name: 'KEC International Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'KALPATPOWR.NS', cleanSymbol: 'KALPATPOWR', name: 'Kalpataru Projects International Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'PNCINFRA.NS', cleanSymbol: 'PNCINFRA', name: 'PNC Infratech Ltd.', sector: 'Infra', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'GRINFRA.NS', cleanSymbol: 'GRINFRA', name: 'G R Infraprojects Ltd.', sector: 'Infra', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'TITAGARH.NS', cleanSymbol: 'TITAGARH', name: 'Titagarh Rail Systems Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TEXRAIL.NS', cleanSymbol: 'TEXRAIL', name: 'Texmaco Rail & Engineering Ltd.', sector: 'Infra', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'JWL.NS', cleanSymbol: 'JWL', name: 'Jupiter Wagons Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'TRITURBINE.NS', cleanSymbol: 'TRITURBINE', name: 'Triveni Turbine Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'THERMAX.NS', cleanSymbol: 'THERMAX', name: 'Thermax Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'AIAENG.NS', cleanSymbol: 'AIAENG', name: 'AIA Engineering Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'TIMKEN.NS', cleanSymbol: 'TIMKEN', name: 'Timken India Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SKFINDIA.NS', cleanSymbol: 'SKFINDIA', name: 'SKF India Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SCHAEFFLER.NS', cleanSymbol: 'SCHAEFFLER', name: 'Schaeffler India Ltd.', sector: 'Infra', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CARBORUNIV.NS', cleanSymbol: 'CARBORUNIV', name: 'Carborundum Universal Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'GRINDWELL.NS', cleanSymbol: 'GRINDWELL', name: 'Grindwell Norton Ltd.', sector: 'Infra', capTier: 'MID_CAP', isFno: false, series: 'EQ' },

  // --- FMCG, CONSUMPTION & RETAIL ---
  { symbol: 'BRITANNIA.NS', cleanSymbol: 'BRITANNIA', name: 'Britannia Industries Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'GODREJCP.NS', cleanSymbol: 'GODREJCP', name: 'Godrej Consumer Products Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'DABUR.NS', cleanSymbol: 'DABUR', name: 'Dabur India Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MARICO.NS', cleanSymbol: 'MARICO', name: 'Marico Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TATACONSUM.NS', cleanSymbol: 'TATACONSUM', name: 'Tata Consumer Products Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'COLPAL.NS', cleanSymbol: 'COLPAL', name: 'Colgate-Palmolive (India) Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'UNITDSPR.NS', cleanSymbol: 'UNITDSPR', name: 'United Spirits Ltd. (Diageo)', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'UBL.NS', cleanSymbol: 'UBL', name: 'United Breweries Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'RADICO.NS', cleanSymbol: 'RADICO', name: 'Radico Khaitan Ltd.', sector: 'FMCG', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'PATANJALI.NS', cleanSymbol: 'PATANJALI', name: 'Patanjali Foods Ltd.', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PGHH.NS', cleanSymbol: 'PGHH', name: 'Procter & Gamble Hygiene & Healthcare', sector: 'FMCG', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'EMAMILTD.NS', cleanSymbol: 'EMAMILTD', name: 'Emami Ltd.', sector: 'FMCG', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'JYOTHYLAB.NS', cleanSymbol: 'JYOTHYLAB', name: 'Jyothy Labs Ltd.', sector: 'FMCG', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'BIKAJI.NS', cleanSymbol: 'BIKAJI', name: 'Bikaji Foods International Ltd.', sector: 'FMCG', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'DEVYANI.NS', cleanSymbol: 'DEVYANI', name: 'Devyani International Ltd.', sector: 'Consumption', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'JUBLFOOD.NS', cleanSymbol: 'JUBLFOOD', name: 'Jubilant FoodWorks Ltd. (Domino\'s)', sector: 'Consumption', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'WESTLIFE.NS', cleanSymbol: 'WESTLIFE', name: 'Westlife Foodworld Ltd. (McDonald\'s)', sector: 'Consumption', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SAPPHIRE.NS', cleanSymbol: 'SAPPHIRE', name: 'Sapphire Foods India Ltd. (KFC/PizzaHut)', sector: 'Consumption', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'RESTAURANT.NS', cleanSymbol: 'RESTAURANT', name: 'Restaurant Brands Asia Ltd. (Burger King)', sector: 'Consumption', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'BERGEPAINT.NS', cleanSymbol: 'BERGEPAINT', name: 'Berger Paints India Ltd.', sector: 'Consumption', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'KANSAINER.NS', cleanSymbol: 'KANSAINER', name: 'Kansai Nerolac Paints Ltd.', sector: 'Consumption', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'PAGEIND.NS', cleanSymbol: 'PAGEIND', name: 'Page Industries Ltd. (Jockey)', sector: 'Consumption', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ABFRL.NS', cleanSymbol: 'ABFRL', name: 'Aditya Birla Fashion & Retail Ltd.', sector: 'Consumption', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'VEDANTFASH.NS', cleanSymbol: 'VEDANTFASH', name: 'Vedant Fashions Ltd. (Manyavar)', sector: 'Consumption', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'BATAINDIA.NS', cleanSymbol: 'BATAINDIA', name: 'Bata India Ltd.', sector: 'Consumption', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'RELAXO.NS', cleanSymbol: 'RELAXO', name: 'Relaxo Footwears Ltd.', sector: 'Consumption', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CAMPUS.NS', cleanSymbol: 'CAMPUS', name: 'Campus Activewear Ltd.', sector: 'Consumption', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'METROBRAND.NS', cleanSymbol: 'METROBRAND', name: 'Metro Brands Ltd.', sector: 'Consumption', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'KALYANKJIL.NS', cleanSymbol: 'KALYANKJIL', name: 'Kalyan Jewellers India Ltd.', sector: 'Consumption', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SENCO.NS', cleanSymbol: 'SENCO', name: 'Senco Gold Ltd.', sector: 'Consumption', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'THANGAMAYL.NS', cleanSymbol: 'THANGAMAYL', name: 'Thangamayil Jewellery Ltd.', sector: 'Consumption', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },

  // --- CHEMICALS, SPECIALTY CHEMICALS & FERTILIZERS ---
  { symbol: 'PIDILITIND.NS', cleanSymbol: 'PIDILITIND', name: 'Pidilite Industries Ltd. (Fevicol)', sector: 'Nifty Chemicals', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SRF.NS', cleanSymbol: 'SRF', name: 'SRF Ltd.', sector: 'Nifty Chemicals', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'DEEPAKNTR.NS', cleanSymbol: 'DEEPAKNTR', name: 'Deepak Nitrite Ltd.', sector: 'Nifty Chemicals', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'NAVINFLUOR.NS', cleanSymbol: 'NAVINFLUOR', name: 'Navin Fluorine International Ltd.', sector: 'Nifty Chemicals', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ATUL.NS', cleanSymbol: 'ATUL', name: 'Atul Ltd.', sector: 'Nifty Chemicals', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'AARTIIND.NS', cleanSymbol: 'AARTIIND', name: 'Aarti Industries Ltd.', sector: 'Nifty Chemicals', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PIIND.NS', cleanSymbol: 'PIIND', name: 'PI Industries Ltd.', sector: 'Nifty Chemicals', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'UPL.NS', cleanSymbol: 'UPL', name: 'UPL Ltd.', sector: 'Nifty Chemicals', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'COROMANDEL.NS', cleanSymbol: 'COROMANDEL', name: 'Coromandel International Ltd.', sector: 'Nifty Chemicals', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CHAMBLFERT.NS', cleanSymbol: 'CHAMBLFERT', name: 'Chambal Fertilisers and Chemicals', sector: 'Nifty Chemicals', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'GNFC.NS', cleanSymbol: 'GNFC', name: 'Gujarat Narmada Valley Fertilizers', sector: 'Nifty Chemicals', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'GSFC.NS', cleanSymbol: 'GSFC', name: 'Gujarat State Fertilizers & Chemicals', sector: 'Nifty Chemicals', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'FACT.NS', cleanSymbol: 'FACT', name: 'Fertilisers and Chemicals Travancore', sector: 'Nifty Chemicals', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'RCFL.NS', cleanSymbol: 'RCFL', name: 'Rashtriya Chemicals and Fertilizers', sector: 'Nifty Chemicals', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'TATACHEM.NS', cleanSymbol: 'TATACHEM', name: 'Tata Chemicals Ltd.', sector: 'Nifty Chemicals', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'FLUOROCHEM.NS', cleanSymbol: 'FLUOROCHEM', name: 'Gujarat Fluorochemicals Ltd.', sector: 'Nifty Chemicals', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'LINDEINDIA.NS', cleanSymbol: 'LINDEINDIA', name: 'Linde India Ltd.', sector: 'Nifty Chemicals', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'FINEORG.NS', cleanSymbol: 'FINEORG', name: 'Fine Organic Industries Ltd.', sector: 'Nifty Chemicals', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CLEAN.NS', cleanSymbol: 'CLEAN', name: 'Clean Science and Technology Ltd.', sector: 'Nifty Chemicals', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ALKYLAMINE.NS', cleanSymbol: 'ALKYLAMINE', name: 'Alkyl Amines Chemicals Ltd.', sector: 'Nifty Chemicals', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'BALAMINES.NS', cleanSymbol: 'BALAMINES', name: 'Balaji Amines Ltd.', sector: 'Nifty Chemicals', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SUMICHEM.NS', cleanSymbol: 'SUMICHEM', name: 'Sumitomo Chemical India Ltd.', sector: 'Nifty Chemicals', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CASTROLIND.NS', cleanSymbol: 'CASTROLIND', name: 'Castrol India Ltd.', sector: 'Nifty Chemicals', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SUPREMEIND.NS', cleanSymbol: 'SUPREMEIND', name: 'Supreme Industries Ltd.', sector: 'Commodities', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ASTRAL.NS', cleanSymbol: 'ASTRAL', name: 'Astral Ltd.', sector: 'Commodities', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'FINPIPE.NS', cleanSymbol: 'FINPIPE', name: 'Finolex Industries Ltd.', sector: 'Commodities', capTier: 'MID_CAP', isFno: false, series: 'EQ' },

  // --- NEW AGE TECH, INTERNET & FINTECH ---
  { symbol: 'PAYTM.NS', cleanSymbol: 'PAYTM', name: 'One97 Communications Ltd. (Paytm)', sector: 'Service Sector', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'POLICYBZR.NS', cleanSymbol: 'POLICYBZR', name: 'PB Fintech Ltd. (PolicyBazaar)', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'NYKAA.NS', cleanSymbol: 'NYKAA', name: 'FSN E-Commerce Ventures Ltd. (Nykaa)', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'DELHIVERY.NS', cleanSymbol: 'DELHIVERY', name: 'Delhivery Ltd.', sector: 'Service Sector', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'NAUKRI.NS', cleanSymbol: 'NAUKRI', name: 'Info Edge (India) Ltd. (Naukri.com)', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'INDIAMART.NS', cleanSymbol: 'INDIAMART', name: 'IndiaMART InterMESH Ltd.', sector: 'Service Sector', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'JUSTDIAL.NS', cleanSymbol: 'JUSTDIAL', name: 'Just Dial Ltd.', sector: 'Service Sector', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CARTRADE.NS', cleanSymbol: 'CARTRADE', name: 'CarTrade Tech Ltd.', sector: 'Service Sector', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'EASEMYTRIP.NS', cleanSymbol: 'EASEMYTRIP', name: 'Easy Trip Planners Ltd.', sector: 'Service Sector', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'IXIGO.NS', cleanSymbol: 'IXIGO', name: 'Le Travenues Technology Ltd. (ixigo)', sector: 'Service Sector', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'FIRSTCRY.NS', cleanSymbol: 'FIRSTCRY', name: 'Brainbees Solutions Ltd. (FirstCry)', sector: 'Service Sector', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'OLAELCTRC.NS', cleanSymbol: 'OLAELCTRC', name: 'Ola Electric Mobility Ltd.', sector: 'Nifty Auto', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SWIGGY.NS', cleanSymbol: 'SWIGGY', name: 'Swiggy Ltd.', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'MAPMYINDIA.NS', cleanSymbol: 'MAPMYINDIA', name: 'C.E. Info Systems Ltd. (MapmyIndia)', sector: 'IT', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'AFFLE.NS', cleanSymbol: 'AFFLE', name: 'Affle (India) Ltd.', sector: 'IT', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ROUTE.NS', cleanSymbol: 'ROUTE', name: 'Route Mobile Ltd.', sector: 'IT', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'TANLA.NS', cleanSymbol: 'TANLA', name: 'Tanla Platforms Ltd.', sector: 'IT', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'RATEGAIN.NS', cleanSymbol: 'RATEGAIN', name: 'RateGain Travel Technologies Ltd.', sector: 'IT', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },

  // --- AVIATION, HOSPITALITY & TOURISM ---
  { symbol: 'INDIGO.NS', cleanSymbol: 'INDIGO', name: 'InterGlobe Aviation Ltd. (IndiGo)', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SPICEJET.NS', cleanSymbol: 'SPICEJET', name: 'SpiceJet Ltd.', sector: 'Service Sector', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'INDHOTEL.NS', cleanSymbol: 'INDHOTEL', name: 'The Indian Hotels Company Ltd. (Taj)', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'EIHOTEL.NS', cleanSymbol: 'EIHOTEL', name: 'EIH Ltd. (Oberoi Hotels)', sector: 'Service Sector', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CHALET.NS', cleanSymbol: 'CHALET', name: 'Chalet Hotels Ltd.', sector: 'Service Sector', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'LEMONTree.NS', cleanSymbol: 'LEMONTREE', name: 'Lemon Tree Hotels Ltd.', sector: 'Service Sector', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SAMHI.NS', cleanSymbol: 'SAMHI', name: 'SAMHI Hotels Ltd.', sector: 'Service Sector', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'JUNIPER.NS', cleanSymbol: 'JUNIPER', name: 'Juniper Hotels Ltd. (Hyatt)', sector: 'Service Sector', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'MAHLOG.NS', cleanSymbol: 'MAHLOG', name: 'Mahindra Logistics Ltd.', sector: 'Service Sector', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'TCI.NS', cleanSymbol: 'TCI', name: 'Transport Corporation of India Ltd.', sector: 'Service Sector', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'BLUEDART.NS', cleanSymbol: 'BLUEDART', name: 'Blue Dart Express Ltd.', sector: 'Service Sector', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ALLCARGO.NS', cleanSymbol: 'ALLCARGO', name: 'Allcargo Logistics Ltd.', sector: 'Service Sector', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },

  // --- MEDIA, ENTERTAINMENT & TELECOM ---
  { symbol: 'ZEEL.NS', cleanSymbol: 'ZEEL', name: 'Zee Entertainment Enterprises Ltd.', sector: 'Nifty Media', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SUNTV.NS', cleanSymbol: 'SUNTV', name: 'Sun TV Network Ltd.', sector: 'Nifty Media', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PVRINOX.NS', cleanSymbol: 'PVRINOX', name: 'PVR INOX Ltd.', sector: 'Nifty Media', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TV18BRDCST.NS', cleanSymbol: 'TV18BRDCST', name: 'TV18 Broadcast Ltd.', sector: 'Nifty Media', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'NETWORK18.NS', cleanSymbol: 'NETWORK18', name: 'Network18 Media & Investments Ltd.', sector: 'Nifty Media', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SAREGAMA.NS', cleanSymbol: 'SAREGAMA', name: 'Saregama India Ltd.', sector: 'Nifty Media', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'TIPSMUSIC.NS', cleanSymbol: 'TIPSMUSIC', name: 'Tips Music Ltd.', sector: 'Nifty Media', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'NAZARA.NS', cleanSymbol: 'NAZARA', name: 'Nazara Technologies Ltd.', sector: 'Nifty Media', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'DBCORP.NS', cleanSymbol: 'DBCORP', name: 'D. B. Corp Ltd. (Dainik Bhaskar)', sector: 'Nifty Media', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'JAGRAN.NS', cleanSymbol: 'JAGRAN', name: 'Jagran Prakashan Ltd.', sector: 'Nifty Media', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'INDUSTOWER.NS', cleanSymbol: 'INDUSTOWER', name: 'Indus Towers Ltd.', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'IDEA.NS', cleanSymbol: 'IDEA', name: 'Vodafone Idea Ltd.', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'TATACOMM.NS', cleanSymbol: 'TATACOMM', name: 'Tata Communications Ltd.', sector: 'Service Sector', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HFCL.NS', cleanSymbol: 'HFCL', name: 'HFCL Ltd.', sector: 'Service Sector', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'STLTECH.NS', cleanSymbol: 'STLTECH', name: 'Sterlite Technologies Ltd.', sector: 'Service Sector', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'TEJASNET.NS', cleanSymbol: 'TEJASNET', name: 'Tejas Networks Ltd.', sector: 'IT', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ITI.NS', cleanSymbol: 'ITI', name: 'ITI Ltd.', sector: 'IT', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'OPTCL.NS', cleanSymbol: 'OPTCL', name: 'Optiemus Infracom Ltd.', sector: 'IT', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },

  // --- HOUSING FINANCE, NBFCs & CAPITAL MARKETS ---
  { symbol: 'LICHSGFIN.NS', cleanSymbol: 'LICHSGFIN', name: 'LIC Housing Finance Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PNBHOUSING.NS', cleanSymbol: 'PNBHOUSING', name: 'PNB Housing Finance Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CANFINHOME.NS', cleanSymbol: 'CANFINHOME', name: 'Can Fin Homes Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'HOMEFIRST.NS', cleanSymbol: 'HOMEFIRST', name: 'Home First Finance Company Ltd.', sector: 'Nifty Financial Services', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'AAVAS.NS', cleanSymbol: 'AAVAS', name: 'Aavas Financiers Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'APTUS.NS', cleanSymbol: 'APTUS', name: 'Aptus Value Housing Finance India', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'HUDCO.NS', cleanSymbol: 'HUDCO', name: 'Housing & Urban Development Corp Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'ABCAPITAL.NS', cleanSymbol: 'ABCAPITAL', name: 'Aditya Birla Capital Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'M&MFIN.NS', cleanSymbol: 'M&MFIN', name: 'Mahindra & Mahindra Financial Services', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'LTF.NS', cleanSymbol: 'LTF', name: 'L&T Finance Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'MANAPPURAM.NS', cleanSymbol: 'MANAPPURAM', name: 'Manappuram Finance Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'IIFL.NS', cleanSymbol: 'IIFL', name: 'IIFL Finance Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SAMMAANCAP.NS', cleanSymbol: 'SAMMAANCAP', name: 'Sammaan Capital Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'SBICARD.NS', cleanSymbol: 'SBICARD', name: 'SBI Cards and Payment Services Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'CREDITACC.NS', cleanSymbol: 'CREDITACC', name: 'CreditAccess Grameen Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'FUSION.NS', cleanSymbol: 'FUSION', name: 'Fusion Micro Finance Ltd.', sector: 'Nifty Financial Services', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SPANDANA.NS', cleanSymbol: 'SPANDANA', name: 'Spandana Sphoorty Financial Ltd.', sector: 'Nifty Financial Services', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'POONAWALLA.NS', cleanSymbol: 'POONAWALLA', name: 'Poonawalla Fincorp Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CHOLAHLDNG.NS', cleanSymbol: 'CHOLAHLDNG', name: 'Cholamandalam Financial Holdings', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'MFSL.NS', cleanSymbol: 'MFSL', name: 'Max Financial Services Ltd.', sector: 'Nifty Financial Services', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'IEX.NS', cleanSymbol: 'IEX', name: 'Indian Energy Exchange Ltd.', sector: 'Nifty Financial Services', capTier: 'MID_CAP', isFno: true, series: 'EQ' },

  // --- CEMENT, CERAMICS & BUILDING MATERIALS ---
  { symbol: 'JKCEMENT.NS', cleanSymbol: 'JKCEMENT', name: 'JK Cement Ltd.', sector: 'Nifty Cement', capTier: 'LARGE_CAP', isFno: true, series: 'EQ' },
  { symbol: 'RAMCOCEM.NS', cleanSymbol: 'RAMCOCEM', name: 'The Ramco Cements Ltd.', sector: 'Nifty Cement', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'BIRLACORPN.NS', cleanSymbol: 'BIRLACORPN', name: 'Birla Corporation Ltd.', sector: 'Nifty Cement', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'HEIDELBERG.NS', cleanSymbol: 'HEIDELBERG', name: 'HeidelbergCement India Ltd.', sector: 'Nifty Cement', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'INDIACEM.NS', cleanSymbol: 'INDIACEM', name: 'The India Cements Ltd.', sector: 'Nifty Cement', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'PRISMCJOHNS.NS', cleanSymbol: 'PRISMCJOHNS', name: 'Prism Johnson Ltd.', sector: 'Nifty Cement', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'STARCEMENT.NS', cleanSymbol: 'STARCEMENT', name: 'Star Cement Ltd.', sector: 'Nifty Cement', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ORIENTCEM.NS', cleanSymbol: 'ORIENTCEM', name: 'Orient Cement Ltd.', sector: 'Nifty Cement', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SAGCEM.NS', cleanSymbol: 'SAGCEM', name: 'Sagar Cements Ltd.', sector: 'Nifty Cement', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'KAJARIACER.NS', cleanSymbol: 'KAJARIACER', name: 'Kajaria Ceramics Ltd.', sector: 'Consumer Durables', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CERA.NS', cleanSymbol: 'CERA', name: 'Cera Sanitaryware Ltd.', sector: 'Consumer Durables', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SOMANYCERA.NS', cleanSymbol: 'SOMANYCERA', name: 'Somany Ceramics Ltd.', sector: 'Consumer Durables', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'CENTURYPLY.NS', cleanSymbol: 'CENTURYPLY', name: 'Century Plyboards (India) Ltd.', sector: 'Commodities', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'GREENPANEL.NS', cleanSymbol: 'GREENPANEL', name: 'Greenpanel Industries Ltd.', sector: 'Commodities', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'GREENPLY.NS', cleanSymbol: 'GREENPLY', name: 'Greenply Industries Ltd.', sector: 'Commodities', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },

  // --- SUGAR, AGRO & TEXTILES ---
  { symbol: 'BALRAMCHIN.NS', cleanSymbol: 'BALRAMCHIN', name: 'Balrampur Chini Mills Ltd.', sector: 'Commodities', capTier: 'MID_CAP', isFno: true, series: 'EQ' },
  { symbol: 'EIDPARRY.NS', cleanSymbol: 'EIDPARRY', name: 'E.I.D. - Parry (India) Ltd.', sector: 'Commodities', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'TRIVENI.NS', cleanSymbol: 'TRIVENI', name: 'Triveni Engineering & Industries Ltd.', sector: 'Commodities', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'RENUKA.NS', cleanSymbol: 'RENUKA', name: 'Shree Renuka Sugars Ltd.', sector: 'Commodities', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'DHAMPURSUG.NS', cleanSymbol: 'DHAMPURSUG', name: 'Dhampur Sugar Mills Ltd.', sector: 'Commodities', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'AVANTIFEED.NS', cleanSymbol: 'AVANTIFEED', name: 'Avanti Feeds Ltd.', sector: 'FMCG', capTier: 'SMALL_CAP', isFno: false, series: 'EQ' },
  { symbol: 'GODREJAGRO.NS', cleanSymbol: 'GODREJAGRO', name: 'Godrej Agrovet Ltd.', sector: 'FMCG', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'KPRMILL.NS', cleanSymbol: 'KPRMILL', name: 'K.P.R. Mill Ltd.', sector: 'Consumption', capTier: 'LARGE_CAP', isFno: false, series: 'EQ' },
  { symbol: 'TRIDENT.NS', cleanSymbol: 'TRIDENT', name: 'Trident Ltd.', sector: 'Consumption', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'WELSPUNLIV.NS', cleanSymbol: 'WELSPUNLIV', name: 'Welspun Living Ltd.', sector: 'Consumption', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'RAYMOND.NS', cleanSymbol: 'RAYMOND', name: 'Raymond Ltd.', sector: 'Consumption', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'GARFIBRES.NS', cleanSymbol: 'GARFIBRES', name: 'Garware Technical Fibres Ltd.', sector: 'Commodities', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'VTL.NS', cleanSymbol: 'VTL', name: 'Vardhman Textiles Ltd.', sector: 'Consumption', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'SWANENERGY.NS', cleanSymbol: 'SWANENERGY', name: 'Swan Energy Ltd.', sector: 'Energy', capTier: 'MID_CAP', isFno: false, series: 'EQ' },
  { symbol: 'ALOKINDS.NS', cleanSymbol: 'ALOKINDS', name: 'Alok Industries Ltd.', sector: 'Consumption', capTier: 'MID_CAP', isFno: false, series: 'EQ' }
];

export const NSE_TOTAL_COUNT = ALL_NSE_STOCKS.length;

export const getNseStocksByUniverse = (universe: string, fetchUniverse?: 'FNO' | 'ALL'): string[] => {
  if (fetchUniverse === 'FNO' && universe === 'ALL_NSE') {
    return ALL_NSE_STOCKS.filter(s => s.isFno).map(s => s.symbol);
  }
  switch (universe) {
    case 'NIFTY_50':
      return ALL_NSE_STOCKS.slice(0, 50).map(s => s.symbol);
    case 'NIFTY_100':
      return ALL_NSE_STOCKS.filter(s => s.capTier === 'LARGE_CAP').slice(0, 100).map(s => s.symbol);
    case 'NIFTY_200':
    case 'NIFTY_FNO':
      return ALL_NSE_STOCKS.filter(s => s.isFno).map(s => s.symbol);
    case 'NIFTY_500':
      return ALL_NSE_STOCKS.slice(0, Math.min(500, ALL_NSE_STOCKS.length)).map(s => s.symbol);
    case 'NIFTY_MIDCAP':
      return ALL_NSE_STOCKS.filter(s => s.capTier === 'MID_CAP').map(s => s.symbol);
    case 'NIFTY_SMALLCAP':
      return ALL_NSE_STOCKS.filter(s => s.capTier === 'SMALL_CAP').map(s => s.symbol);
    case 'ALL_NSE':
      return ALL_NSE_STOCKS.map(s => s.symbol);
    case 'US_TECH':
      return ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'META', 'TSLA', 'AMD', 'NFLX', 'SPY'];
    default:
      return ALL_NSE_STOCKS.map(s => s.symbol);
  }
};
